### ISSUE TITLE
Sentry "There was 1 error encountered while processing this event"

### ISSUE THREAD

**Issue by ramonsaraiva** [jmagnusson/sentry-dramatiq#1]
![image](https://user-images.githubusercontent.com/5559120/57233643-672a3200-6ff5-11e9-9c7c-b6588ef0c6d1.png)

I'm receiving this error when visualizing a logger `.error(..)` in Sentry.

That is probably avoiding Sentry from collecting those context values.

**Comment by jacobsvante** [comment]
Thanks for the bug report!

To clarify, do you mean that this happens when you use a `logger.error` statement in your task? If so - could you perhaps include some code for me to look at? I was unable to reproduce with a simple `logging.error` statement in a task.

**Comment by ramonsaraiva** [comment]
I used the same logger dramatiq recommends using.

```
@dramatiq.actor
def task():
    task.logger.error(..)
```

Edit: see https://github.com/Bogdanp/dramatiq/blob/master/examples/time_limit/example.py#L15 as reference

**Comment by ramonsaraiva** [comment]
@jmagnusson any idea?

**Comment by jacobsvante** [comment]
Hi @ramonsaraiva I haven't had a chance to look at this, busy days. 

Does it work if you use the standard logger? I.e:

```python
import logging

logger = logging.getLogger(__name__)

@dramatiq.actor
def task():
    logger.error(..)
```

**Comment by untitaker** [comment]
I think #2 is the root cause for this one.

**Comment by jacobsvante** [comment]
@ramonsaraiva Does 0.3.0 fix this issue for you?

**Comment by ramonsaraiva** [comment]
I'll check @jmagnusson

**Comment by ramonsaraiva** [comment]
The error still remains when using the task logger `task_function.logger.error(..)`
![image](https://user-images.githubusercontent.com/5559120/59940911-59f4c580-9432-11e9-8e8b-d96fe19964e8.png)

The same happens when instantiating a logger myself:
```
import logging
logger = logging.getLogger(__name__)

@dramatiq.actor(
    queue_name=queues.Queue.HEALTHCHECK.value,
    max_retries=1,
    min_backoff=queues.Backoff.FIFTEEN_SECONDS.value,
    max_backoff=queues.Backoff.TWO_MINUTES.value,
)
def healthcheck():
    logger.error('hello im a test!', extra={'hi': 'there'})
```

**Comment by untitaker** [comment]
I don't think you successfully updated the extension. Further down in the event it should show you a list of installed packages.

**Comment by ramonsaraiva** [comment]
![image](https://user-images.githubusercontent.com/5559120/59941307-40a04900-9433-11e9-9910-271ce9851a40.png)

**Comment by untitaker** [comment]
Ah, this line needs to be removed: https://github.com/untitaker/sentry-dramatiq/blob/f155cbba2be13ef4a78f5b67fee91db91437694f/sentry_dramatiq/__init__.py#L118

**Comment by untitaker** [comment]
Opened pr at #5

**Comment by untitaker** [comment]
@ramonsaraiva could you take a screenshot of how the job information at the bottom of the event looks now? There should be a new "dramatiq" section

**Comment by ramonsaraiva** [comment]
I don't have a computer with me atm. Tomorrow morning I'll do that and post it here.

**Comment by ramonsaraiva** [comment]
@untitaker 

![image](https://user-images.githubusercontent.com/5559120/60012831-4f654680-9653-11e9-9b7c-b57535a9146f.png)

**Comment by untitaker** [comment]
hmmm could you share that event with me (markus@sentry.io)? This seems broken in the UI unless the JSON download also contains `[object Object]`

**Comment by ramonsaraiva** [comment]
I don't think I have the required access in our sentry org to share an event. I know there is a feature to do that but I can't see any link for it.

**Comment by untitaker** [comment]
You can just copypaste the regular link you visit and send it to me, I as a Sentry employee can access it.

**Comment by untitaker** [comment]
Ah, you have your own on-prem instance, I can't help with that. We would have to have a backdoor into on-prem instances, which would be very concerning!

Which version of Sentry are you running?

**Comment by ramonsaraiva** [comment]
8.22.0, I'm also using the new SDK 0.6.9

**Comment by untitaker** [comment]
Those are both outdated, we have Sentry 9.1.1 and sentry-sdk 0.9.0 nowadays :)

I think you need to upgrade sentry for this to work, or we change sentry-dramatiq to work with Sentry 8 again.

**Comment by ramonsaraiva** [comment]
Makes sense. I'm pretty sure we have some constraints for upgrading sentry to 9, because of legacy projects. I appreciate the heads up, anyways.
