### ISSUE TITLE
Looking for a new maintainer / merge into sentry-sdk or dramatiq

### ISSUE THREAD

**Issue by jacobsvante** [jmagnusson/sentry-dramatiq#10]
Having just become a father in addition to working 100% full time I'm basically unable to maintain this package in a way that's beneficial to the community.

Preferably I think this code would do best to live in [sentry-python](https://github.com/getsentry/sentry-python) or [dramatiq](https://github.com/Bogdanp/dramatiq).

@untitaker @Bogdanp what do you think?

**Comment by untitaker** [comment]
I can help co-maintain but I don't think it's popular enough to merge into the SDK

**Comment by jacobsvante** [comment]
@untitaker Perfect. I've added you as a collaborator. What's your PyPI username?

**Comment by ramonsaraiva** [comment]
I can help as well if needed.

**Comment by jacobsvante** [comment]
Great @ramonsaraiva! What’s your PyPI username?

**Comment by ramonsaraiva** [comment]
@jmagnusson ramonsaraiva :-)

**Comment by jacobsvante** [comment]
@ramonsaraiva done!

**Comment by jacobsvante** [comment]
Thank @untitaker and @ramonsaraiva for stepping up! I think three maintainers should be enough to ensure the project’s longevity so I’ll go ahead and close this now.
