### ISSUE TITLE
Tests broken on master?

### ISSUE THREAD

**Issue by dimrozakis** [jmagnusson/sentry-dramatiq#9]
The tests from #8 failed in the same way as those from the unrelated #6. Furthermore, I get the exact same failures locally, even with master checked out. As far as I can see, the last travis ci pipeline on master ran 8 months ago. @jmagnusson can you please trigger a pipeline on master to see if it still passes?

**Comment by jacobsvante** [comment]
@dimrozakis build retriggered - master is also failing.

Please see #10

**Comment by ramonsaraiva** [comment]
see https://github.com/jmagnusson/sentry-dramatiq/issues/12
